# Generated by Django 3.0.2 on 2020-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='id',
                                           primary_key=True, serialize=False)),
                ('company', models.CharField(db_column='company', max_length=60)),
                ('model', models.CharField(db_column='model', max_length=60)),
                ('product_year', models.IntegerField(db_column='product_year')),
            ],
        ),
    ]
