# Generated by Django 3.0.2 on 2020-01-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('price', models.FloatField(db_column='price')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.ForeignKey(default=None, null=True, on_delete=str, to='api.CarPrice'),
            preserve_default=False,
        ),
    ]
